name: build ios2222

on:
	push:
		branches:
			-main

jobs:
	build:
		runs-on: macos-latest
		steps:
			-uses:actions/checkout@v2
			-name:Install Flutter
			run:git clone ~/flutter
			-name:Setup Flutter
			run: ~/flutter/bin/flutter pub get
			-name: build ios
			run:~/flutter/bin/flutter build ios --release